name: spawn-tests
on:
  pull_request:
    branches: ["master"]
  push:

jobs:

  spawn-install:
    strategy:
      fail-fast: false  # https://github.com/actions/runner-images#available-images
      matrix:  # https://www.lua.org/versions.html
        os: [ubuntu-latest]
        lua-version: [5.1, 5.2, 5.3, 5.4, 5.5]
        include:
          - os: macos-latest
            lua-version: 5.1
          - os: macos-latest
            lua-version: 5.5
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "${{ runner.os }} on ${{ runner.arch }}"
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: luarocks/gh-actions-lua@master
        with:
          luaVersion: ${{ matrix.lua-version }}
      - uses: luarocks/gh-actions-luarocks@master
        with:
          luaRocksVersion: "3.13.0"
      - run: lua -v && luarocks --version
      - run: luarocks lint spawn-scm-0.rockspec
      # Install the local version of compat53.
      - run: luarocks --local make spawn-scm-0.rockspec
      - run: luarocks list && luarocks show spawn
      - run: luarocks --local remove spawn
